name: Publish Doker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/MaksimYakushenkov/next-test/next-test
          username: ${{ secrets.DOKER_NAME }}
          password: ${{ secrets.DOKER_PASSWORD }}
          tags: "develop"